# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

# Tabular 1 vez para el nombre del servicio
  # Tabular 2 veces para el resto
  app.service.calculator_services:
    class: AppBundle\Service\CalculatorServices